### ISSUE TITLE
Improve photo mode

### ISSUE THREAD

**Issue by jordanehara** [jordanehara/window-sim#17]
**Description**: Currently the user can't take a picture of elements on the edges of the screen and there is no smoothness to a "flick" movement to pan the background with the mouse. To improve this, move the "photo zone" around with mouse movement and pan the background with WASD instead of right mouse drag.

**Acceptance Criteria**:
- Panning the background within the bounds of the background sprite with WASD. The photo zone should stay in the bounds of the current camera
- Move the photo zone with mouse movement within the bounds of the current camera
- Update the camera so that it takes a picture where the photo zone is.
- Zoom in where the mouse position is.

**Tasks**:
- [x] Dev Tasks
  - [x] Move the photo zone with mouse movement
  - [ ] ~~Pan the background with WASD~~
  - [x] Take a picture in the photo zone
  - [ ] ~~Zoom into mouse position~~
