### ISSUE TITLE
Spring Version

### ISSUE THREAD

**Issue by jordanehara** [jordanehara/window-sim#2]
**Description**: The spring version is the base version of the game. It contains more greenery and wildlife occasionally appearing. Raining occasionally - sometimes for more than one day.

**Tasks**:
- [ ] UI Design
  - [ ] Spring background
  - [ ] Spring little dudes
  - [ ] Object toggle animations
  - [ ] Rain version
  - [ ] Apply to computer dates
- [ ] Dev Tasks
  - [ ] Toggle lights on/off
  - [ ] Open/Close windows
  - [ ] Things sway a little if the windows are open
